# Generated by Django 4.2.20 on 2025-06-01 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_xp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('answer', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('не начато', 'Не начато'), ('в процессе', 'В процессе'), ('завершено', 'Завершено')], default='не начато', max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'managed': True,
                'unique_together': {('user', 'case')},
            },
        ),
        migrations.CreateModel(
            name='AvailableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.case')),
            ],
            options={
                'managed': True,
                'unique_together': {('case', 'table')},
            },
        ),
    ]
