# Generated by Django 5.2.2 on 2025-08-08 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "xp",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(
                        default="Краткое описание отсутствует", max_length=255
                    ),
                ),
                (
                    "required_xp",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "reward_xp",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("answer", models.CharField(max_length=50)),
            ],
            options={
                "managed": True,
                "indexes": [
                    models.Index(fields=["title"], name="users_case_title_a2745c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailableTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(max_length=50)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.case"
                    ),
                ),
            ],
            options={
                "managed": True,
                "indexes": [
                    models.Index(fields=["case"], name="users_avail_case_id_a4a855_idx")
                ],
                "unique_together": {("case", "table")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("не начато", "Не начато"),
                            ("в процессе", "В процессе"),
                            ("завершено", "Завершено"),
                        ],
                        default="не начато",
                        max_length=20,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.case"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["case", "status"], name="users_userp_case_id_a9c848_idx"
                    ),
                    models.Index(
                        fields=["case", "user"], name="users_userp_case_id_c0a4ae_idx"
                    ),
                    models.Index(
                        fields=["user"], name="users_userp_user_id_156ffc_idx"
                    ),
                ],
                "unique_together": {("user", "case")},
            },
        ),
    ]
