# Generated by Django 5.2.2 on 2025-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabletable',
            index=models.Index(fields=['case'], name='users_avail_case_id_a4a855_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['title'], name='users_case_title_a2745c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['case', 'status'], name='users_userp_case_id_a9c848_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['case', 'user'], name='users_userp_case_id_c0a4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user'], name='users_userp_user_id_156ffc_idx'),
        ),
    ]
