# Generated by Django 5.2.2 on 2025-09-01 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'XP не может быть отрицательным')]),
        ),
    ]
