# Generated by Django 5.2.2 on 2025-08-08 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="номер статьи закона.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="описание содержания статьи."),
                ),
            ],
            options={
                "db_table": "article",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ФИO человека.",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Location can only contain latin letters, cyrillic letters and hyphen",
                                regex="^[a-zA-Zа-яА-Я\\-]*$",
                            )
                        ],
                    ),
                ),
                ("date_birth", models.DateField(help_text="дата рождения.")),
                (
                    "description",
                    models.TextField(
                        help_text="Подробное описание человека: его внешний вид, привычки, работа."
                    ),
                ),
            ],
            options={
                "db_table": "person",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="описание дела и его обстоятельств."),
                ),
                (
                    "date_opened",
                    models.DateField(help_text="дата открытия уголовного дела."),
                ),
                (
                    "date_closed",
                    models.DateField(help_text="дата закрытия дела.", null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("убийство", "Убийство"),
                            ("кража", "Кража"),
                            ("мошенничество", "Мошенничество"),
                            ("нападение", "Нападение"),
                            ("разбой", "Разбой"),
                            ("поджог", "Поджог"),
                            ("похищение", "Похищение"),
                            ("коррупция", "Коррупция"),
                            ("киберпреступность", "Киберпреступность"),
                            ("шпионаж", "Шпионаж"),
                            ("терроризм", "Терроризм"),
                            ("уклонение от налогов", "Уклонение от уплаты налогов"),
                            ("взяточничество", "Взяточничество"),
                            ("присвоение или растрата", "Присвоение или растрата"),
                            ("вандализм", "Вандализм"),
                            ("незаконная торговля", "Незаконная торговля"),
                            ("торговля людьми", "Торговля людьми"),
                            ("другое", "Другое"),
                        ],
                        help_text="тип преступления, связанного с делом: кража, похищение...",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("открыто", "Открыто"),
                            ("закрыто", "Закрыто"),
                            ("приостановлено", "Приостановлено"),
                        ],
                        default="открыто",
                        help_text="текущий процессуальный статус дела: открыто, закрыто, приостановлено.",
                        max_length=15,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("не раскрыто", "Не раскрыто"),
                            ("раскрыто", "Раскрыто"),
                        ],
                        default="не раскрыто",
                        help_text="отражает результат дела: раскрыто, не раскрыто.",
                        max_length=11,
                    ),
                ),
            ],
            options={
                "db_table": "cases",
                "managed": True,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_closed__gte", models.F("date_opened")),
                            ("date_closed__isnull", True),
                            _connector="OR",
                        ),
                        name="date_closed_after_date_opened",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CrimeScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="адрес места преступления.",
                        max_length=300,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Location can only contain latin letters, cyrillic letters, digits, spaces, and punctuation marks.",
                                regex="^[a-zA-Zа-яА-Я0-9\\s\\.,;?!:\\-()]*$",
                            )
                        ],
                    ),
                ),
                ("date", models.DateField(help_text="дата преступления.")),
                (
                    "case",
                    models.ForeignKey(
                        help_text="дело, к которому относится место преступления.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.case",
                    ),
                ),
            ],
            options={
                "db_table": "crime_scene",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("физическое", "Физическое"),
                            ("цифровое", "Цифровое"),
                            ("показания", "Показания"),
                            ("документальное", "Документальное"),
                            ("видеозапись", "Видеозапись"),
                            ("аудиозапись", "Аудиозапись"),
                            ("следы", "Следы"),
                            ("биологическое", "Биологическое"),
                            ("днк", "ДНК"),
                            ("фотографическое", "Фотографическое"),
                            ("электронное", "Электронное"),
                            ("другое", "Другое"),
                        ],
                        help_text="тип доказательства, связанного с делом: физическое, цифровое...",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(help_text="описание доказательства.")),
                ("date", models.DateField(help_text="Дата получения доказательства.")),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="место преступления, где было найдено доказательство.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.crimescene",
                    ),
                ),
            ],
            options={
                "db_table": "evidence",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("в розыске", "В розыске"),
                            ("арестован", "Арестован"),
                            ("освобожден", "Освобожден"),
                            ("на свободе", "на свободе"),
                            ("выпущен под залог", "Выпущен под залог"),
                        ],
                        help_text="статус подозреваемого в рамках дела: в розыске, арестован...",
                        max_length=21,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        help_text="человек, связанный с этим подозреваемым.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.person",
                    ),
                ),
            ],
            options={
                "db_table": "suspect",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_accusation",
                    models.DateField(help_text="дата предъявления обвинения."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ожидает решения", "Ожидает решения"),
                            ("осужден", "Осужден"),
                            ("отклонено", "Отклонено"),
                            ("прекращено", "Прекращено"),
                            ("аннулировано", "Аннулировано"),
                            ("перенесено", "Перенесено"),
                            ("обжаловано", "Обжаловано"),
                        ],
                        help_text="текущий статус обвинения: осужден, отклонено...",
                        max_length=17,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="cтатья, по которой выдвинуто обвинение.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.article",
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        help_text="подозреваемый, против которого выдвинуто обвинение.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.suspect",
                    ),
                ),
            ],
            options={
                "db_table": "charge",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Alibi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("подтверждено", "Подтверждено"),
                            ("не подтверждено", "Не подтверждено"),
                            ("ложное", "Ложное"),
                        ],
                        help_text="cтатус алиби: подтверждено, не подтверждено, ложное.",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="описание алиби и обстоятельств."),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="дело, к которому относится алиби.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.case",
                    ),
                ),
                (
                    "suspect",
                    models.OneToOneField(
                        help_text="подозреваемый, для которого указывается алиби.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.suspect",
                    ),
                ),
            ],
            options={
                "db_table": "alibi",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SuspectCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="дело, к которому относится подозреваемый.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.case",
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        help_text="подозреваемый, связанный с делом.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.suspect",
                    ),
                ),
            ],
            options={
                "db_table": "suspect_cases",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="suspect",
            name="cases",
            field=models.ManyToManyField(
                through="investigations.SuspectCase", to="investigations.case"
            ),
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField(help_text="текст показания.")),
                (
                    "date_of_statement",
                    models.DateField(help_text="дата предоставления показания."),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="дело, к которому относится показания.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.case",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="человек, давший заявление.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigations.person",
                    ),
                ),
            ],
            options={
                "db_table": "statement",
                "managed": True,
                "unique_together": {("case", "person")},
            },
        ),
    ]
