# Generated by Django 5.2.2 on 2025-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='investigation_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
