# Generated by Django 5.2.2 on 2025-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='short_description',
            field=models.CharField(default='Краткое описание отсутствует', max_length=255),
        ),
    ]
