# Generated by Django 5.2.2 on 2025-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_availabletable_users_avail_case_id_a4a855_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='updated',
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
