# Generated by Django 4.2.20 on 2025-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_case_reward_xd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='reward_xd',
            new_name='reward_xp',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='answers',
        ),
    ]
