# Generated by Django 5.2.2 on 2025-06-09 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Location can only contain latin letters, cyrillic letters and hyphen', regex='^[a-zA-Zа-яА-Я\\-]*$')])),
                ('date_birth', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField(null=True)),
                ('type', models.CharField(choices=[('убийство', 'Убийство'), ('кража', 'Кража'), ('мошенничество', 'Мошенничество'), ('нападение', 'Нападение'), ('разбой', 'Разбой'), ('поджог', 'Поджог'), ('похищение', 'Похищение'), ('коррупция', 'Коррупция'), ('киберпреступность', 'Киберпреступность'), ('шпионаж', 'Шпионаж'), ('терроризм', 'Терроризм'), ('уклонение от налогов', 'Уклонение от уплаты налогов'), ('взяточничество', 'Взяточничество'), ('присвоение или растрата', 'Присвоение или растрата'), ('вандализм', 'Вандализм'), ('незаконная торговля', 'Незаконная торговля'), ('торговля людьми', 'Торговля людьми'), ('другое', 'Другое')], max_length=30)),
                ('status', models.CharField(choices=[('открыто', 'Открыто'), ('закрыто', 'Закрыто'), ('приостановлено', 'Приостановлено')], default='открыто', max_length=15)),
            ],
            options={
                'db_table': 'case',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('date_closed__gte', models.F('date_opened')), ('date_closed__isnull', True), _connector='OR'), name='date_closed_after_date_opened')],
            },
        ),
        migrations.CreateModel(
            name='CrimeScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Location can only contain latin letters, cyrillic letters, digits, spaces, and punctuation marks.', regex='^[a-zA-Zа-яА-Я0-9\\s\\.,;?!:\\-()]*$')])),
                ('date', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.case')),
            ],
            options={
                'db_table': 'crime_scene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('физическое', 'Физическое'), ('цифровое', 'Цифровое'), ('показания', 'Показания'), ('документальное', 'Документальное'), ('видеозапись', 'Видеозапись'), ('аудиозапись', 'Аудиозапись'), ('следы', 'Следы'), ('биологическое', 'Биологическое'), ('днк', 'ДНК'), ('фотографическое', 'Фотографическое'), ('электронное', 'Электронное'), ('другое', 'Другое')], max_length=15)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.crimescene')),
            ],
            options={
                'db_table': 'evidence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('в розыске', 'В розыске'), ('арестован', 'Арестован'), ('освобожден', 'Освобожден'), ('на свободе', 'на свободе'), ('выпущен под залог', 'Выпущен под залог')], max_length=21)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigations.person')),
            ],
            options={
                'db_table': 'suspect',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accusation', models.DateField()),
                ('status', models.CharField(choices=[('ожидает решения', 'Ожидает решения'), ('осуждён', 'Осуждён'), ('отклонено', 'Отклонено'), ('прекращено', 'Прекращено'), ('аннулировано', 'Аннулировано'), ('перенесено', 'Перенесено'), ('обжаловано', 'Обжаловано')], max_length=17)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.article')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect')),
            ],
            options={
                'db_table': 'charge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('подтверждено', 'Подтверждено'), ('не подтверждено', 'Не подтверждено'), ('ложное', 'Ложное')], max_length=15)),
                ('description', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.case')),
                ('suspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect')),
            ],
            options={
                'db_table': 'alibi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuspectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect')),
            ],
            options={
                'db_table': 'suspect_case',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='suspect',
            name='cases',
            field=models.ManyToManyField(through='investigations.SuspectCase', to='investigations.case'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('date_of_statement', models.DateField()),
                ('alibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.alibi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.person')),
            ],
            options={
                'db_table': 'statement',
                'managed': True,
                'unique_together': {('alibi', 'person')},
            },
        ),
    ]
