# Generated by Django 5.2.2 on 2025-06-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suspectcase',
            table='suspect_cases',
        ),
    ]
