# Generated by Django 5.2.2 on 2025-06-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='cases',
        ),
    ]
