# Generated by Django 5.2.2 on 2025-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
