# Generated by Django 5.2.2 on 2025-06-14 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_alter_case_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='resolution',
            field=models.CharField(choices=[('не раскрыто', 'Не раскрыто'), ('раскрыто', 'Раскрыто')], default='не раскрыто', help_text='отражает результат дела: раскрыто, не раскрыто.', max_length=11),
        ),
        migrations.AlterField(
            model_name='alibi',
            name='case',
            field=models.ForeignKey(help_text='дело, к которому относится алиби.', on_delete=django.db.models.deletion.CASCADE, to='investigations.case'),
        ),
        migrations.AlterField(
            model_name='alibi',
            name='description',
            field=models.TextField(help_text='описание алиби и обстоятельств.'),
        ),
        migrations.AlterField(
            model_name='alibi',
            name='status',
            field=models.CharField(choices=[('подтверждено', 'Подтверждено'), ('не подтверждено', 'Не подтверждено'), ('ложное', 'Ложное')], help_text='cтатус алиби: подтверждено, не подтверждено, ложное.', max_length=15),
        ),
        migrations.AlterField(
            model_name='alibi',
            name='suspect',
            field=models.OneToOneField(help_text='подозреваемый, для которого указывается алиби.', on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(help_text='описание содержания статьи.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(help_text='номер статьи закона.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_closed',
            field=models.DateField(help_text='дата закрытия дела.', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_opened',
            field=models.DateField(help_text='дата открытия уголовного дела.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(help_text='описание дела и его обстоятельств.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('открыто', 'Открыто'), ('закрыто', 'Закрыто'), ('приостановлено', 'Приостановлено')], default='открыто', help_text='текущий процессуальный статус дела: открыто, закрыто, приостановлено', max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('убийство', 'Убийство'), ('кража', 'Кража'), ('мошенничество', 'Мошенничество'), ('нападение', 'Нападение'), ('разбой', 'Разбой'), ('поджог', 'Поджог'), ('похищение', 'Похищение'), ('коррупция', 'Коррупция'), ('киберпреступность', 'Киберпреступность'), ('шпионаж', 'Шпионаж'), ('терроризм', 'Терроризм'), ('уклонение от налогов', 'Уклонение от уплаты налогов'), ('взяточничество', 'Взяточничество'), ('присвоение или растрата', 'Присвоение или растрата'), ('вандализм', 'Вандализм'), ('незаконная торговля', 'Незаконная торговля'), ('торговля людьми', 'Торговля людьми'), ('другое', 'Другое')], help_text='тип преступления, связанного с делом: кража, похищение...', max_length=30),
        ),
        migrations.AlterField(
            model_name='charge',
            name='article',
            field=models.ForeignKey(help_text='cтатья, по которой выдвинуто обвинение.', on_delete=django.db.models.deletion.CASCADE, to='investigations.article'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='date_accusation',
            field=models.DateField(help_text='дата предъявления обвинения.'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('ожидает решения', 'Ожидает решения'), ('осужден', 'Осужден'), ('отклонено', 'Отклонено'), ('прекращено', 'Прекращено'), ('аннулировано', 'Аннулировано'), ('перенесено', 'Перенесено'), ('обжаловано', 'Обжаловано')], help_text='текущий статус обвинения: осужден, отклонено...', max_length=17),
        ),
        migrations.AlterField(
            model_name='charge',
            name='suspect',
            field=models.ForeignKey(help_text='подозреваемый, против которого выдвинуто обвинение.', on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect'),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='case',
            field=models.ForeignKey(help_text='дело, к которому относится место преступления.', on_delete=django.db.models.deletion.CASCADE, to='investigations.case'),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='date',
            field=models.DateField(help_text='дата преступления.'),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='location',
            field=models.CharField(help_text='адрес места преступления.', max_length=300, validators=[django.core.validators.RegexValidator(message='Location can only contain latin letters, cyrillic letters, digits, spaces, and punctuation marks.', regex='^[a-zA-Zа-яА-Я0-9\\s\\.,;?!:\\-()]*$')]),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='date',
            field=models.DateField(help_text='Дата получения доказательства.'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(help_text='описание доказательства.'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='scene',
            field=models.ForeignKey(help_text='место преступления, где было найдено доказательство.', on_delete=django.db.models.deletion.CASCADE, to='investigations.crimescene'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.CharField(choices=[('физическое', 'Физическое'), ('цифровое', 'Цифровое'), ('показания', 'Показания'), ('документальное', 'Документальное'), ('видеозапись', 'Видеозапись'), ('аудиозапись', 'Аудиозапись'), ('следы', 'Следы'), ('биологическое', 'Биологическое'), ('днк', 'ДНК'), ('фотографическое', 'Фотографическое'), ('электронное', 'Электронное'), ('другое', 'Другое')], help_text='тип доказательства, связанного с делом: физическое, цифровое...', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(help_text='дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(help_text='Подробное описание человека: его внешний вид, привычки, работа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='ФИO человека', max_length=100, validators=[django.core.validators.RegexValidator(message='Location can only contain latin letters, cyrillic letters and hyphen', regex='^[a-zA-Zа-яА-Я\\-]*$')]),
        ),
        migrations.AlterField(
            model_name='statement',
            name='alibi',
            field=models.ForeignKey(help_text='алиби, к которому относится показания.', on_delete=django.db.models.deletion.CASCADE, to='investigations.alibi'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date_of_statement',
            field=models.DateField(help_text='дата предоставления показания.'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='person',
            field=models.ForeignKey(help_text='человек, давший заявление.', on_delete=django.db.models.deletion.CASCADE, to='investigations.person'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement',
            field=models.TextField(help_text='текст показания.'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='person',
            field=models.OneToOneField(help_text='человек, связанный с этим подозреваемым.', on_delete=django.db.models.deletion.CASCADE, to='investigations.person'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('в розыске', 'В розыске'), ('арестован', 'Арестован'), ('освобожден', 'Освобожден'), ('на свободе', 'на свободе'), ('выпущен под залог', 'Выпущен под залог')], help_text='статус подозреваемого в рамках дела: в розыске, арестован...', max_length=21),
        ),
        migrations.AlterField(
            model_name='suspectcase',
            name='case',
            field=models.ForeignKey(help_text='дело, к которому относится подозреваемый.', on_delete=django.db.models.deletion.CASCADE, to='investigations.case'),
        ),
        migrations.AlterField(
            model_name='suspectcase',
            name='suspect',
            field=models.ForeignKey(help_text='подозреваемый, связанный с делом.', on_delete=django.db.models.deletion.CASCADE, to='investigations.suspect'),
        ),
    ]
