# Generated by Django 5.2.2 on 2025-06-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_case_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_description',
        ),
    ]
