# Generated by Django 5.2.2 on 2025-06-14 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_case_resolution_alter_alibi_case_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alibi',
            old_name='case',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='alibi',
            old_name='suspect',
            new_name='suspect_id',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='suspect',
            new_name='suspect_id',
        ),
        migrations.RenameField(
            model_name='crimescene',
            old_name='case',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='scene',
            new_name='scene_id',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='alibi',
            new_name='alibi_id',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='suspectcase',
            old_name='case',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='suspectcase',
            old_name='suspect',
            new_name='suspect_id',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('открыто', 'Открыто'), ('закрыто', 'Закрыто'), ('приостановлено', 'Приостановлено')], default='открыто', help_text='текущий процессуальный статус дела: открыто, закрыто, приостановлено.', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(help_text='дата рождения.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(help_text='Подробное описание человека: его внешний вид, привычки, работа.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='ФИO человека.', max_length=100, validators=[django.core.validators.RegexValidator(message='Location can only contain latin letters, cyrillic letters and hyphen', regex='^[a-zA-Zа-яА-Я\\-]*$')]),
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('alibi_id', 'person_id')},
        ),
    ]
