# Generated by Django 5.2.2 on 2025-06-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_remove_case_case_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='investigations_case',
        ),
    ]
