# Generated by Django 5.2.2 on 2025-06-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_alter_case_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='case',
        ),
    ]
