# Generated by Django 5.2.2 on 2025-06-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_rename_case_alibi_case_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alibi',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='alibi',
            old_name='suspect_id',
            new_name='suspect',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='suspect_id',
            new_name='suspect',
        ),
        migrations.RenameField(
            model_name='crimescene',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='scene_id',
            new_name='scene',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='alibi_id',
            new_name='alibi',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='suspectcase',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='suspectcase',
            old_name='suspect_id',
            new_name='suspect',
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('alibi', 'person')},
        ),
    ]
