# Generated by Django 5.2.2 on 2025-06-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0006_case_investigation_plan_case_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='investigation_plan',
        ),
        migrations.RemoveField(
            model_name='case',
            name='short_description',
        ),
    ]
