--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Homebrew)
-- Dumped by pg_dump version 14.18 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alibi; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.alibi (
    id bigint NOT NULL,
    status character varying(15) NOT NULL,
    description text NOT NULL,
    case_id bigint NOT NULL,
    suspect_id bigint NOT NULL
);


ALTER TABLE public.alibi OWNER TO sqlhunt;

--
-- Name: alibi_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.alibi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alibi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.article (
    id integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.article OWNER TO sqlhunt;

--
-- Name: cases; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.cases (
    id bigint NOT NULL,
    description text NOT NULL,
    date_opened date NOT NULL,
    date_closed date,
    type character varying(30) NOT NULL,
    status character varying(15) NOT NULL,
    resolution character varying(11) NOT NULL,
    CONSTRAINT date_closed_after_date_opened CHECK (((date_closed >= date_opened) OR (date_closed IS NULL)))
);


ALTER TABLE public.cases OWNER TO sqlhunt;

--
-- Name: cases_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: charge; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.charge (
    id bigint NOT NULL,
    date_accusation date NOT NULL,
    status character varying(17) NOT NULL,
    article_id integer NOT NULL,
    suspect_id bigint NOT NULL
);


ALTER TABLE public.charge OWNER TO sqlhunt;

--
-- Name: charge_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.charge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.charge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crime_scene; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.crime_scene (
    id bigint NOT NULL,
    location character varying(300) NOT NULL,
    date date NOT NULL,
    case_id bigint NOT NULL
);


ALTER TABLE public.crime_scene OWNER TO sqlhunt;

--
-- Name: crime_scene_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.crime_scene ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crime_scene_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidence; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.evidence (
    id bigint NOT NULL,
    type character varying(15) NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    scene_id bigint NOT NULL
);


ALTER TABLE public.evidence OWNER TO sqlhunt;

--
-- Name: evidence_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.evidence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    date_birth date NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.person OWNER TO sqlhunt;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statement; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.statement (
    id bigint NOT NULL,
    statement text NOT NULL,
    date_of_statement date NOT NULL,
    case_id bigint NOT NULL,
    person_id bigint NOT NULL
);


ALTER TABLE public.statement OWNER TO sqlhunt;

--
-- Name: statement_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.statement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suspect; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.suspect (
    id bigint NOT NULL,
    status character varying(21) NOT NULL,
    person_id bigint NOT NULL
);


ALTER TABLE public.suspect OWNER TO sqlhunt;

--
-- Name: suspect_cases; Type: TABLE; Schema: public; Owner: sqlhunt
--

CREATE TABLE public.suspect_cases (
    id bigint NOT NULL,
    case_id bigint NOT NULL,
    suspect_id bigint NOT NULL
);


ALTER TABLE public.suspect_cases OWNER TO sqlhunt;

--
-- Name: suspect_case_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.suspect_cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspect_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suspect_id_seq; Type: SEQUENCE; Schema: public; Owner: sqlhunt
--

ALTER TABLE public.suspect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alibi alibi_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.alibi
    ADD CONSTRAINT alibi_pkey PRIMARY KEY (id);


--
-- Name: alibi alibi_suspect_id_key; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.alibi
    ADD CONSTRAINT alibi_suspect_id_key UNIQUE (suspect_id);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: cases cases_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_pkey PRIMARY KEY (id);


--
-- Name: charge charge_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.charge
    ADD CONSTRAINT charge_pkey PRIMARY KEY (id);


--
-- Name: crime_scene crime_scene_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.crime_scene
    ADD CONSTRAINT crime_scene_pkey PRIMARY KEY (id);


--
-- Name: evidence evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: statement statement_case_id_person_id_f153e4f4_uniq; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.statement
    ADD CONSTRAINT statement_case_id_person_id_f153e4f4_uniq UNIQUE (case_id, person_id);


--
-- Name: statement statement_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.statement
    ADD CONSTRAINT statement_pkey PRIMARY KEY (id);


--
-- Name: suspect_cases suspect_case_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect_cases
    ADD CONSTRAINT suspect_case_pkey PRIMARY KEY (id);


--
-- Name: suspect suspect_person_id_key; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect
    ADD CONSTRAINT suspect_person_id_key UNIQUE (person_id);


--
-- Name: suspect suspect_pkey; Type: CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect
    ADD CONSTRAINT suspect_pkey PRIMARY KEY (id);


--
-- Name: alibi_case_id_a75f29a7; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX alibi_case_id_a75f29a7 ON public.alibi USING btree (case_id);


--
-- Name: charge_article_id_9dc08b71; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX charge_article_id_9dc08b71 ON public.charge USING btree (article_id);


--
-- Name: charge_suspect_id_1e1578ef; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX charge_suspect_id_1e1578ef ON public.charge USING btree (suspect_id);


--
-- Name: crime_scene_case_id_912c9c62; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX crime_scene_case_id_912c9c62 ON public.crime_scene USING btree (case_id);


--
-- Name: evidence_scene_id_340f6f0e; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX evidence_scene_id_340f6f0e ON public.evidence USING btree (scene_id);


--
-- Name: statement_case_id_c2e60fe0; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX statement_case_id_c2e60fe0 ON public.statement USING btree (case_id);


--
-- Name: statement_person_id_84f7e9f1; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX statement_person_id_84f7e9f1 ON public.statement USING btree (person_id);


--
-- Name: suspect_case_case_id_4f131009; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX suspect_case_case_id_4f131009 ON public.suspect_cases USING btree (case_id);


--
-- Name: suspect_case_suspect_id_81185fdc; Type: INDEX; Schema: public; Owner: sqlhunt
--

CREATE INDEX suspect_case_suspect_id_81185fdc ON public.suspect_cases USING btree (suspect_id);


--
-- Name: alibi alibi_case_id_a75f29a7_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.alibi
    ADD CONSTRAINT alibi_case_id_a75f29a7_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alibi alibi_suspect_id_544ab797_fk_suspect_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.alibi
    ADD CONSTRAINT alibi_suspect_id_544ab797_fk_suspect_id FOREIGN KEY (suspect_id) REFERENCES public.suspect(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: charge charge_article_id_9dc08b71_fk_article_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.charge
    ADD CONSTRAINT charge_article_id_9dc08b71_fk_article_id FOREIGN KEY (article_id) REFERENCES public.article(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: charge charge_suspect_id_1e1578ef_fk_suspect_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.charge
    ADD CONSTRAINT charge_suspect_id_1e1578ef_fk_suspect_id FOREIGN KEY (suspect_id) REFERENCES public.suspect(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crime_scene crime_scene_case_id_912c9c62_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.crime_scene
    ADD CONSTRAINT crime_scene_case_id_912c9c62_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evidence evidence_scene_id_340f6f0e_fk_crime_scene_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_scene_id_340f6f0e_fk_crime_scene_id FOREIGN KEY (scene_id) REFERENCES public.crime_scene(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: statement statement_case_id_c2e60fe0_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.statement
    ADD CONSTRAINT statement_case_id_c2e60fe0_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: statement statement_person_id_84f7e9f1_fk_person_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.statement
    ADD CONSTRAINT statement_person_id_84f7e9f1_fk_person_id FOREIGN KEY (person_id) REFERENCES public.person(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suspect_cases suspect_case_case_id_4f131009_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect_cases
    ADD CONSTRAINT suspect_case_case_id_4f131009_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suspect_cases suspect_case_suspect_id_81185fdc_fk_suspect_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect_cases
    ADD CONSTRAINT suspect_case_suspect_id_81185fdc_fk_suspect_id FOREIGN KEY (suspect_id) REFERENCES public.suspect(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suspect suspect_person_id_54a9744e_fk_person_id; Type: FK CONSTRAINT; Schema: public; Owner: sqlhunt
--

ALTER TABLE ONLY public.suspect
    ADD CONSTRAINT suspect_person_id_54a9744e_fk_person_id FOREIGN KEY (person_id) REFERENCES public.person(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

